[build]
builder = "NIXPACKS"
watchPatterns = ["frontend/**"]

[build.nixpacksPlan]
providers = ["node"]

[deploy]
startCommand = "cd frontend && npm run build && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
